import Head from 'next/head'

export default function Home() {
  return (
    <div className="w-full h-full min-h-screen flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="m-5">gm</h1>
    </div>
  )
}
